[FORMATTING]
highlight_color=yellow
small_size=6
large_size=11
paragraph_integrity=true
pilcrows=false


[KEYBINDS] 
settings=CTRL ,
vim=true
paste=f2
condense=f3
pocket_hotkey=f4
hat=f5
block=f6
tag=f7
cite=f8
underline=f9
emphasis=f10
highlight=f11
clear=f12
delete_tags=ALT f7
new_document=CRTL n
start_timer=CTRL SHFT t
open_stats=CTRL SHIFT i
shrink=ALT f3
cite_from_link=CTRL f8
wikifi=ALT CTRL SHFT w
