[FORMATTING]
highlight_color=yellow
small_size=6
large_size=11
paragraph_integrity=true
pilcrows=false
theme=nord
theme_color_mode=minimal


vim_lines=false

[KEYBINDS]
settings=CTRL ,
vim=false

[KEYBINDS: GENERAL]
sidebar=CTRL SHFT b
new_document=CTRL n
close_tab=CTRL w
save=CTRL s
save_as=CTRL SHFT s
find=CTRL f
find_and_replace=CTRL h
zoom_in=CTRL =
zoom_out=CTRL -
zoom_reset=CTRL 0

[KEYBINDS: EDITING]
copy=CTRL c
cut=CTRL x
paste_raw=CTRL v
undo=CTRL z
redo=CTRL y
select_all=CTRL a

[KEYBINDS: TEXT FORMATTING]
bold=CTRL b
underline=CTRL u
shrink=ALT f3
clear=f12

[KEYBINDS: CARD STYLES]
paste=f2
condense=f3
pocket_hotkey=f4
hat=f5
block=f6
tag=f7
cite=f8
emphasis=f10

[KEYBINDS: HIGHLIGHTING]
highlight=f11

[KEYBINDS: CASELIST TOOLS]
delete_tags=ALT f7
start_timer=CTRL SHFT t
open_stats=CTRL SHFT i
cite_from_link=CTRL f8
wikifi=CTRL SHFT ALT w

